// <auto-generated />
using System;
using LMBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LMBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622045204_CleanStart")]
    partial class CleanStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LMBackend.Models.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_chat_rooms");

                    b.ToTable("chat_rooms", "public");
                });

            modelBuilder.Entity("LMBackend.Models.DocumentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_document_files");

                    b.HasIndex("ChatRoomId")
                        .HasDatabaseName("ix_document_files_chat_room_id");

                    b.ToTable("document_files", "public");
                });

            modelBuilder.Entity("LMBackend.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response");

                    b.Property<string>("SearchSources")
                        .HasColumnType("text")
                        .HasColumnName("search_sources");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserInput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_input");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ChatRoomId")
                        .HasDatabaseName("ix_messages_chat_room_id");

                    b.ToTable("messages", "public");
                });

            modelBuilder.Entity("LMBackend.Models.DocumentFile", b =>
                {
                    b.HasOne("LMBackend.Models.ChatRoom", "ChatRoom")
                        .WithMany("DocumentFiles")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_files_chat_rooms_chat_room_id");

                    b.Navigation("ChatRoom");
                });

            modelBuilder.Entity("LMBackend.Models.Message", b =>
                {
                    b.HasOne("LMBackend.Models.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_chat_rooms_chat_room_id");

                    b.Navigation("ChatRoom");
                });

            modelBuilder.Entity("LMBackend.Models.ChatRoom", b =>
                {
                    b.Navigation("DocumentFiles");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
