approvals:
  mode: manual
context:
  enabled: true
mcp_servers:
  everything-to-md-converter:
    enabled: true
    url: http://ainexus.phison.com:5155/api/v1/Agent/mcp/2295/MTIwOTA6MTc4NDEwOTEwNA.5BiSODXCP7FwaMac9Es4foYw7aaK5pE1aC5qeEoDWuU
  image-generator:
    enabled: true
    url: http://ainexus.phison.com:5155/api/v1/Agent/mcp/254/MTIwOTA6MTc4NDEwOTEwNA.5BiSODXCP7FwaMac9Es4foYw7aaK5pE1aC5qeEoDWuU
  sequential-thinking:
    args:
    - -y
    - '@modelcontextprotocol/server-sequential-thinking'
    command: npx
    enabled: true
  websearch:
    enabled: true
    url: http://ainexus.phison.com:5155/api/v1/Agent/mcp/4/MTIwOTA6MTc4NDEwOTEwNA.5BiSODXCP7FwaMac9Es4foYw7aaK5pE1aC5qeEoDWuU
memory:
  memory_enabled: true
  nudge_interval: 10
  provider: ''
  user_profile_enabled: true
  write_approval: true
model:
  api_key: AINX-F78D2FCD53915EE37BD0871392FFBFFAF648C53C388950FC6A1F2ED8C534B249
  base_url: https://ainexus.phison.com/api/external/v1
  default: Qwen/Qwen3.6-35B-A3B-FP8
  provider: custom
skills:
  write_approval: true
terminal:
  backend: local
  cwd: /workspace
  persistent_shell: true
  timeout: 180
tools:
  enabled:
  - file_read
  - file_write
  - file_edit
  - patch_code_file
  - view_code_item
  - grep_search
  - bash
