memory:
  memory_enabled: true
  provider: ''
  user_profile_enabled: true
  write_approval: false
model:
  api_key: AINX-F78D2FCD53915EE37BD0871392FFBFFAF648C53C388950FC6A1F2ED8C534B249
  base_url: https://ainexus.phison.com/api/external/v1
  default: Qwen/Qwen3.6-35B-A3B-FP8
  provider: custom
skills:
  write_approval: false
terminal:
  auth_method: password
  backend: ssh
  cwd: /workspace
  host: 127.0.0.1
  password: Justin123456!
  persistent_shell: true
  port: 22
  timeout: 180
  user: justin_zhang
tools:
  enabled:
  - file_read
  - file_write
  - file_edit
  - patch_code_file
  - view_code_item
  - grep_search
  - bash
